CREATE TABLE zaps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    npub TEXT NOT NULL,
    receipt_id TEXT NOT NULL,
    zapped_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    amount INTEGER NOT NULL
);
